version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - '/share/docker/alist:/opt/alist/data'
            - '/share/Alist:/alist'
        ports:
            - '5244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: alist
        image: 'xhofe/alist:latest'