version: '3.3'
services:
    emby:
        image: 'amilys/embyserver:beta'
        container_name: emby
        network_mode: host
        restart: always
        devices:
            - "/dev/dri:/dev/dri"
        ports:
            - '8096:8096'
        volumes:
            - '/share/docker/emby:/config'
            - '/share/Movie:/downloads'